/* eslint-disable perfectionist/sort-objects */
const MATCH_STATUS_GENERAL = {
  // 0-19
  NOT_STARTED: 0,
  FINAL: 1,
  DELAYED: 2,
  CANCELLED: 3,
  OTHER: 4,
  INTERRUPTED: 5,
  HALFTIME: 6,
};

export const FOOTBALL_MATCH_STATUS = {
  ...MATCH_STATUS_GENERAL,
  // 20-39
  FIRST_HALF: 20,
  SECOND_HALF: 22,
  AWAITING_EXTRA_TIME: 23,
  FIRST_EXTRA_TIME: 24,
  HALFTIME_EXTRA_TIME: 25,
  SECOND_EXTRA_TIME: 26,
  FINAL_EXTRA_TIME: 27,
  AWAITING_PENALTIES: 28,
  PENALTIES: 29,
  FINAL_PENALTIES: 30,
};

export const MATCH_STATUS_LABELS = {
  [FOOTBALL_MATCH_STATUS.AWAITING_EXTRA_TIME]: "TE",
  [FOOTBALL_MATCH_STATUS.AWAITING_PENALTIES]: "Pen",
  [FOOTBALL_MATCH_STATUS.FINAL_EXTRA_TIME]: "Fim TE",
  [FOOTBALL_MATCH_STATUS.FINAL_PENALTIES]: "Fim Pen",
  [FOOTBALL_MATCH_STATUS.FIRST_EXTRA_TIME]: "1TE",
  [FOOTBALL_MATCH_STATUS.FIRST_HALF]: "1T",
  [FOOTBALL_MATCH_STATUS.HALFTIME]: "Int",
  [FOOTBALL_MATCH_STATUS.HALFTIME_EXTRA_TIME]: "Int TE",
  [FOOTBALL_MATCH_STATUS.PENALTIES]: "Pen",
  [FOOTBALL_MATCH_STATUS.SECOND_EXTRA_TIME]: "2TE",
  [FOOTBALL_MATCH_STATUS.SECOND_HALF]: "2T",
  [MATCH_STATUS_GENERAL.CANCELLED]: "Cancel",
  [MATCH_STATUS_GENERAL.DELAYED]: "Adiado",
  [MATCH_STATUS_GENERAL.FINAL]: "Fim",
  [MATCH_STATUS_GENERAL.INTERRUPTED]: "Interr",
  [MATCH_STATUS_GENERAL.NOT_STARTED]: "",
  [MATCH_STATUS_GENERAL.OTHER]: "Outro",
};

export const MATCH_STATUS = {
  AWAITING_EXTRA_TIME: FOOTBALL_MATCH_STATUS.AWAITING_EXTRA_TIME,
  AWAITING_PENALTIES: FOOTBALL_MATCH_STATUS.AWAITING_PENALTIES,
  PENALTIES: FOOTBALL_MATCH_STATUS.PENALTIES,
  FINAL_PENALTIES: FOOTBALL_MATCH_STATUS.FINAL_PENALTIES,
  CANCELLED: MATCH_STATUS_GENERAL.CANCELLED,
  DELAYED: MATCH_STATUS_GENERAL.DELAYED,
  FINAL: MATCH_STATUS_GENERAL.FINAL,
  FIRST_HALF: FOOTBALL_MATCH_STATUS.FIRST_HALF,
  HALFTIME: FOOTBALL_MATCH_STATUS.HALFTIME,
  SECOND_HALF: FOOTBALL_MATCH_STATUS.SECOND_HALF,
  FIRST_EXTRA_TIME: FOOTBALL_MATCH_STATUS.FIRST_EXTRA_TIME,
  SECOND_EXTRA_TIME: FOOTBALL_MATCH_STATUS.SECOND_EXTRA_TIME,
  FINAL_EXTRA_TIME: FOOTBALL_MATCH_STATUS.FINAL_EXTRA_TIME,
  HALFTIME_EXTRA_TIME: FOOTBALL_MATCH_STATUS.HALFTIME_EXTRA_TIME,
  NOT_STARTED: MATCH_STATUS_GENERAL.NOT_STARTED,
  OTHER: MATCH_STATUS_GENERAL.OTHER,
};

export const STOPPED_GAME = [
  MATCH_STATUS.FINAL,
  MATCH_STATUS.FINAL_EXTRA_TIME,
  MATCH_STATUS.FINAL_PENALTIES,
  MATCH_STATUS.CANCELLED,
  MATCH_STATUS.HALFTIME,
  MATCH_STATUS.DELAYED,
  MATCH_STATUS.NOT_STARTED,
  MATCH_STATUS.HALFTIME_EXTRA_TIME,
];

export const FINISHED_GAME = [MATCH_STATUS.FINAL, MATCH_STATUS.FINAL_EXTRA_TIME, MATCH_STATUS.FINAL_PENALTIES];

export const FIFA_STAGES_ID = {
  1: 289273, // Group stage
  2: 289273, // Group stage
  3: 289273, // Group stage
  4: 289287, // Round of 32
  5: 289288, // Round of 16
  6: 289289, // Quarter-finals
  7: 289290, // Semi-finals
  8: 289291, // Third place play-off
  9: 289292, // Final
};

/*
FIFA API Periods
1 ?
2: Pre-match
3: 1st Half
4: Halftime
5: 2nd Half
6: Awaiting Extra Time
7: 1st Extra Time
8: Halftime Extra Time
9: 2nd Extra Time
10: FINAL
11: Penalties
12: Final Penalties
*/

export type TMatchStatus = MatchStatus;
type MatchStatus = (typeof MATCH_STATUS)[keyof typeof MATCH_STATUS];
